### ISSUE TITLE
Only run `node app.js` once

### ISSUE THREAD

**Issue by claviska** [lukewatts/postleaf-docker#1]
Well done, sir!

Re: https://github.com/lukewatts/postleaf-docker/blob/master/Dockerfile#L65-L68

I believe this is happening because Postleaf creates certain directories on startup, namely the `data` directory. You can probably fix this by creating all required directories _before_ changing permissions:

- `data/`
- `uploads/`
- `themes/`
- `cache/`

That should be all of them!

**Comment by lukewatts** [comment]
I was thinking that was probably the reason. I'll spin up another build with those directories pre-installed and see if it works. It should.

**Comment by lukewatts** [comment]
@claviska Nope. I've added those directories just after running `gulp build` and then set the permissions after but it fails with the same DB error as before. So still requires a failed `RUN node app.js`.

Perhaps the permission are wrong. Perhaps it should be `www-data:$USER` ??

**Comment by lukewatts** [comment]
No that's not it either. It's weird. I can't think of what it could be.

**Comment by claviska** [comment]
I usually chown the containing directory since it should be owned by `www-data` anyways. Assuming, for example, Postleaf is located in `/var/www/postleaf`:

```
chown -R $USER:www-data /var/www
```

But in theory, only changing `/var/www/postleaf` _should_ be enough. 🤔

**Comment by claviska** [comment]
I could move directory creation to the build process instead of on startup. That may make more sense and would still keep them out of the git repo. Let me know if you get it sorted.

**Comment by lukewatts** [comment]
Maybe...

I'm gonna spend the evening reading up on Linux permissions and Docker and see if anything jumps out at me.

**Comment by claviska** [comment]
@abecks might have some insight on this.

**Comment by lukewatts** [comment]
Perhaps more debugging output from Postleaf on what it's doing on startup might help. Like a flag `--log` so it logs to a file or something.

Thinking out loud so ignore me if that's stupid :)

**Comment by lukewatts** [comment]
Although logging to a file might run into the same issues...

**Comment by claviska** [comment]
Not stupid, if `NODE_ENV` is dev it probably should. Can you see the result of `console.log` when the container is setting up?

**Comment by lukewatts** [comment]
On closer inspection it appears the `chown` command isn't working correctly. I stripped it back to stop just after the change in permissions should have taken effect and an `ls -la` shows `root:root` as the permissions still.

I know there are some quirks with permission in a Docker container so I'll do some more digging. That's where the problem is.

**Comment by lukewatts** [comment]
After some searching over on Docker issues I think I've found the cause. 

https://github.com/moby/moby/issues/28513

So because I'm using the official nginx container as a base the www-data is is not affected by crown in the calling Dockerfile.

So I might need to use a make a different base file and pull in nginx manually.

**Comment by claviska** [comment]
I usually start with a clean VPS and install it manually anyway. You can use the config from the [DO tutorial](https://www.postleaf.org/installing-postleaf-on-digitalocean) if it helps.

Next big task will be automating SSL (also covered in that article, so maybe a --domain and --ssl flag?)

**Comment by lukewatts** [comment]
I think eventually it might be better to use Docker compose for a production setup

**Comment by lukewatts** [comment]
@claviska Is there anyway the database.sq3 file can be created in it's initial state before `node app.js` is ran? I think because the way volumes behave this would be the best way.

If not I'll have to bundle it with the repo and copy it into the build but I'm not sure if SQLite3 has data it sets on creation which could cause conflicts.

**Comment by lukewatts** [comment]
I can confirm copying the file in just before creating the volumes solves the problem. So I'm going to add this change to the repo and maybe downthe line a change in the Postleaf setup process might solve this in a more centralized way.

**Comment by claviska** [comment]
That won't really work, and here's why. Sequelize is the ORM that interfaces with the database, so it's actually possible (with minor code changes) to use SQLite, MySQL, MSSQL, or PostgreSQL. The database is created with the `sync` method, so the process will vary depending on the database.

While it's true that this doesn't matter in a container environment, it's important because I'm not really able to change how that works without dropping future support for those databases.

What you can probably do for the container is create an empty file called `data/database.sq3` and set permissions. On startup, Sequelize _should_ sync and create the tables it needs anyway.

If not, I can probably create an empty database file from my SQLite app and use that. I'd prefer not to commit a binary file or a file with a schema (since that's defined in the models and would need to be updated separately), but it may be necessary in this case.

**Comment by lukewatts** [comment]
We'll I've added the `database.sq3` in its initial state to the repo which gets pulled in on build. A blank file won't work because there's data in it when it's created that needs to be there. Not ideal for sure because if some one runs the container without that file in `html/data` the database will be deleted on the container

**Comment by claviska** [comment]
> Is there anyway the database.sq3 file can be created in it's initial state before node app.js is ran?

Been thinking about this. It should be possible with a short custom module that uses `source/modules/database.php`. The code that initializes the database is in the `init` method:

https://github.com/Postleaf/postleaf/blob/master/source/modules/database.js#L29-L36

So, running a script that calls `Database.init()` before the app starts up will create the database file for you with the correct schema. Once the database is created, it's benign to run `init` again so it won't affect startup to use it twice.

**Comment by lukewatts** [comment]
So that reminded me of a possible Postleaf feature I was thinking about yesterday.

https://github.com/Postleaf/postleaf/issues/27

A command which could be run from the console would be ideal. Such as `postleaf init` which does the necessary db setup before running `node app.js`.
